use std::fs;
use anyhow::Result;
use crate::models::AgentsManifest;

pub fn generate_agents_md(manifest: &AgentsManifest, output_path: &str) -> Result<()> {
    let content = render_markdown(manifest);
    fs::write(output_path, &content)?;
    println!("   ✓ Written to {}", output_path);
    Ok(())
}

pub fn render_markdown(m: &AgentsManifest) -> String {
    let mut out = String::new();

    out.push_str(&format!("# AGENTS.md — {}\n\n", m.name));
    out.push_str(&format!("> {}\n\n", m.description));

    if let Some(version) = &m.version {
        out.push_str(&format!("**Version:** {}\n\n", version));
    }

    out.push_str("---\n\n");

    if let Some(auth) = &m.authentication {
        out.push_str("## Authentication\n\n");
        out.push_str(&format!("**Type:** `{}`\n\n", auth.r#type));
        if let Some(desc) = &auth.description {
            out.push_str(&format!("{}\n\n", desc));
        }
        out.push_str("---\n\n");
    }

    if !m.capabilities.is_empty() {
        out.push_str("## Capabilities\n\n");
        out.push_str("What an agent can do with this repository:\n\n");

        for cap in &m.capabilities {
            out.push_str(&format!("### `{}`\n\n", cap.name));
            out.push_str(&format!("{}\n\n", cap.description));

            if let Some(input) = &cap.input_schema {
                out.push_str("**Input:**\n\n");
                out.push_str("```json\n");
                out.push_str(&serde_json::to_string_pretty(input).unwrap_or_default());
                out.push_str("\n```\n\n");
            }

            if let Some(output) = &cap.output_schema {
                out.push_str("**Output:**\n\n");
                out.push_str("```json\n");
                out.push_str(&serde_json::to_string_pretty(output).unwrap_or_default());
                out.push_str("\n```\n\n");
            }

            if !cap.examples.is_empty() {
                out.push_str("**Examples:**\n\n");
                for ex in &cap.examples {
                    out.push_str(&format!("- {}\n", ex));
                }
                out.push('\n');
            }
        }

        out.push_str("---\n\n");
    }

    if !m.endpoints.is_empty() {
        out.push_str("## Endpoints\n\n");

        for ep in &m.endpoints {
            out.push_str(&format!(
                "### `{} {}`\n\n{}\n\n",
                ep.method.to_uppercase(),
                ep.path,
                ep.description
            ));

            if !ep.parameters.is_empty() {
                out.push_str("| Parameter | Type | Required | Description |\n");
                out.push_str("|-----------|------|----------|-------------|\n");
                for p in &ep.parameters {
                    out.push_str(&format!(
                        "| `{}` | `{}` | {} | {} |\n",
                        p.name,
                        p.r#type,
                        if p.required { "✅" } else { "❌" },
                        p.description
                    ));
                }
                out.push('\n');
            }
        }

        out.push_str("---\n\n");
    }

    if let Some(rl) = &m.rate_limits {
        out.push_str("## Rate Limits\n\n");
        if let Some(rpm) = rl.requests_per_minute {
            out.push_str(&format!("- **Per minute:** {}\n", rpm));
        }
        if let Some(rpd) = rl.requests_per_day {
            out.push_str(&format!("- **Per day:** {}\n", rpd));
        }
        if let Some(notes) = &rl.notes {
            out.push_str(&format!("\n{}\n", notes));
        }
        out.push_str("\n---\n\n");
    }

    if let Some(contact) = &m.contact {
        out.push_str(&format!("## Contact\n\n{}\n\n---\n\n", contact));
    }

    out.push_str("*Generated by [Beacon](https://github.com/BeaconOnBase/beacon) — Make any repo agent-ready. Instantly.*\n");

    out
}
