use anyhow::Result;
use crate::models::ValidationResult;

pub fn validate_file(path: &str) -> Result<ValidationResult> {
    let content = std::fs::read_to_string(path)
        .map_err(|_| anyhow::anyhow!("Could not read file: {}", path))?;

    validate_content(&content)
}

pub fn validate_content(content: &str) -> Result<ValidationResult> {
    let mut errors: Vec<String> = vec![];
    let mut warnings: Vec<String> = vec![];

    if !content.contains("# AGENTS.md") && !content.lines().any(|l| l.starts_with("# ")) {
        errors.push("Missing top-level # heading".to_string());
    }

    if !content.lines().any(|l| l.starts_with("> ")) {
        warnings.push("No description blockquote found (recommended: > Your description)".to_string());
    }

    if !content.contains("## Capabilities") {
        errors.push("Missing ## Capabilities section".to_string());
    }

    if content.contains("## Capabilities") {
        let caps_count = content.matches("### `").count();
        if caps_count == 0 {
            warnings.push("Capabilities section is empty — no capabilities declared".to_string());
        }
    }

    if content.contains("## Endpoints") {
        let valid_methods = ["GET", "POST", "PUT", "DELETE", "PATCH"];
        
        let in_endpoints_section = content
            .split("## Endpoints")
            .nth(1)
            .unwrap_or("");

        let endpoint_lines: Vec<&str> = in_endpoints_section
            .lines()
            .filter(|l| l.starts_with("### `"))
            .collect();

        for line in &endpoint_lines {
            let has_method = valid_methods.iter().any(|m| line.contains(m));
            if !has_method {
                warnings.push(format!(
                    "Endpoint missing HTTP method: {}",
                    line.trim_start_matches("### `").trim_end_matches('`')
                ));
            }
        }
    }

    if !content.contains("Generated by") {
        warnings.push("Missing generator footer".to_string());
    }

    let valid = errors.is_empty();

    if valid {
        println!("   ✅ Schema valid");
    } else {
        println!("   ❌ {} error(s) found", errors.len());
    }

    if !warnings.is_empty() {
        println!("   ⚠️  {} warning(s)", warnings.len());
    }

    Ok(ValidationResult {
        valid,
        errors,
        warnings,
    })
}
